### ISSUE TITLE
test: *.raw and *.cub versions of same image

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/socet_gxp_dev#15]
DoD:
  
Raw and cub work the same

**Comment by dgaluszkaUSGS** [comment]
suggest:  rename *.cub and *.raw image versions (to be able to identify separately throughout workflow) prior to import.

- [ ] Upon import, use split screen mode to compare "a priori" feature location (lat/lon/elev) across *.raw and *.cub version of same image.
- [ ] Compare solutions (at each stage of control) using same *.gpf between 2 image versions
- [ ]  Compare image behavior at all phases througout workflow

**Comment by thareUSGS** [comment]
this has been well tested. Both *.raw or *.cub work for importing or dragging images into the interface. This implies that the they also have a _filename__keywords.lis next to the *.raw or *.cub files.
