### ISSUE TITLE
streamline pcalign using GXP exports

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/socet_gxp_dev#21]

**Comment by thareUSGS** [comment]
Can we export CSV from GXP for PC align (selected set or not).

**Comment by dpmayerUSGS** [comment]
@thareUSGS Do we need to keep this issue open?
I'm trying to consolidate issues related to pc_align under the "SurfaceFit Refactor/Reimplementation" project. 

The initial Python port of SurfaceFit (#42 ) has demonstrated that we can successfully transform GPFs and Socet ASCII DTMs into pc_align compatible formats via plio's GPF reader and Pandas. I also have a new issue opened (#44 ) about enabling support for other point cloud/DTM formats for SurfaceFit.

**Comment by thareUSGS** [comment]
support for the original workflow has been enabled. Updates to this routine to allow for user changes to the workflow will continue to be added.
