### ISSUE TITLE
support for updates to Socet GXP gpf file

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/socet_gxp_dev#46]
The current gpf reader in plio (as written by Socet SET) needs an update to support extra "header" lines in the output gpf from Socet GXP. Support for a Socet SET or GXP gpf file should be invisible to the user but allow for the user to ask which version was sent.

**Comment by dpmayerUSGS** [comment]
This should be added as an issue on plio's repository because we're using their reader/writer for GPF support.
If we decide we need our own interim solution (say, in the SurfaceFit script), let's be explicit about that in an issue.

**Comment by dpmayerUSGS** [comment]
@thareUSGS I've opened an issue on the plio repository: https://github.com/USGS-Astrogeology/plio/issues/24
