### ISSUE TITLE
Binaries in repo

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/socet_gxp_dev#48]
This repo contains binary files. They are small, but given the way that git handles binary data that does not matter - they will cause issues.  I would remove them and purge them from the history.

**Comment by dpmayerUSGS** [comment]
@jlaura The only binaries in the repo are compiled versions of some of the code in the graveyard subdirectory of SurfaceFit. We've included them for posterity (they're the last known copies that "worked") and they aren't something that would be updated.

As long as we police PRs and make sure those files aren't changed, is there still a practical harm in keeping them there?
