### ISSUE TITLE
TopoMouse on GXP

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/socet_gxp_dev#5]
DoD:
  - [x] Shorty
  - [x] Temple
  - [x] Notes on what mice we have (USB/Serial) 
  - [x] notes on how to setup mice 
see: https://github.com/USGS-Astrogeology/socet_gxp_dev/wiki/3D-Mouse-Setup

  - [ ] ~~Stealth / Topo configuration and button mapping~~
  - [x] Notes to make sure SSet and SGXP both work

**Comment by thareUSGS** [comment]
We know in SocetSet, we must use legacy USB driver (see ...)

**Comment by thareUSGS** [comment]
On the Wiki lets get function mapping to our 3D mice written down. e.g. documented like this:
Multiport : "Snap Stereo Cursor To Ground" : "Leica Topomouse(USB) Button 4"
or
Multiport : "Snap Stereo Cursor To Ground" : "Stealth Mouse (Z-Type) Button 7"

**Comment by dgaluszkaUSGS** [comment]
Trent, there are too many functions to document every button mapping.
There needs to be a better way to do this.

- Donna

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Donna Galuszka
 U.S. Geological Survey, Astrogeology Science Center
 2255 North Gemini Drive
 Flagstaff, AZ  86001
 928.556.7394 / dgaluszka@usgs.gov
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by thareUSGS** [comment]
My point is there are only 8  or 10 mouse buttons on the mice to map. That
is all that needs to be documented. I wasn't sure how Socet Set buttons
have been setup so I need to rely on you guys to emulate your settings in
GXP.

**Comment by thareUSGS** [comment]
figured out newest driver wasn't uninstalled. Needed old driver 3.x. Don't use 4.x

**Comment by dpmayerUSGS** [comment]
Closing because this was marked as Done >2 years ago.
